const {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  AlignmentType,
  PageBreak,
  Header,
  Footer,
  PageNumber,
  NumberFormat,
  convertInchesToTwip,
  ShadingType,
} = require('docx');
const fs = require('fs');

// Cores do tema FURIOUS
const COLORS = {
  fury: 'FF2D20',
  gold: 'FFD700',
  night: '0A0A1A',
  graphite: '1E1E2E',
  cyan: '00E5FF',
  text: 'F0F0F0',
  gray: '9CA3AF',
  common: '9CA3AF',
  special: '3B82F6',
  epic: '8B5CF6',
  legendary: 'F59E0B',
  furious: 'FF2D20',
};

const createHeading = (text, level) => {
  const sizes = { 1: 36, 2: 28, 3: 24, 4: 20, 5: 18 };
  return new Paragraph({
    text,
    heading: level,
    spacing: { before: 400, after: 200 },
    style: `Heading${level}`,
  });
};

const createParagraph = (text, options = {}) => {
  return new Paragraph({
    children: [new TextRun({ text, color: COLORS.text, size: 22, font: 'Inter' })],
    spacing: { before: 100, after: 100 },
    ...options,
  });
};

const createBullet = (text, level = 0) => {
  return new Paragraph({
    text,
    bullet: { level },
    spacing: { before: 50, after: 50 },
  });
};

const createTableCell = (text, options = {}) => {
  return new TableCell({
    children: [new Paragraph({
      children: [new TextRun({ text, color: COLORS.text, size: 20, font: 'Inter' })],
      alignment: AlignmentType.LEFT,
    })],
    shading: options.shading ? { fill: options.shading, type: ShadingType.CLEAR } : undefined,
    borders: {
      top: { style: BorderStyle.SINGLE, size: 1, color: '333333' },
      bottom: { style: BorderStyle.SINGLE, size: 1, color: '333333' },
      left: { style: BorderStyle.SINGLE, size: 1, color: '333333' },
      right: { style: BorderStyle.SINGLE, size: 1, color: '333333' },
    },
    margins: { top: 50, bottom: 50, left: 100, right: 100 },
  });
};

const createTableHeader = (text, width = 2000) => {
  return new TableCell({
    children: [new Paragraph({
      children: [new TextRun({ text, bold: true, color: COLORS.night, size: 20, font: 'Inter' })],
      alignment: AlignmentType.CENTER,
    })],
    shading: { fill: COLORS.fury, type: ShadingType.CLEAR },
    borders: {
      top: { style: BorderStyle.SINGLE, size: 1, color: COLORS.fury },
      bottom: { style: BorderStyle.SINGLE, size: 1, color: COLORS.fury },
      left: { style: BorderStyle.SINGLE, size: 1, color: COLORS.fury },
      right: { style: BorderStyle.SINGLE, size: 1, color: COLORS.fury },
    },
    width: { size: width, type: WidthType.DXA },
    margins: { top: 50, bottom: 50, left: 100, right: 100 },
  });
};

const doc = new Document({
  styles: {
    paragraphStyles: [
      {
        id: 'Heading1',
        name: 'Heading 1',
        basedOn: 'Normal',
        next: 'Normal',
        run: { size: 36, bold: true, color: COLORS.fury, font: 'Bebas Neue' },
        paragraph: { spacing: { before: 400, after: 200 } },
      },
      {
        id: 'Heading2',
        name: 'Heading 2',
        basedOn: 'Normal',
        next: 'Normal',
        run: { size: 28, bold: true, color: COLORS.gold, font: 'Bebas Neue' },
        paragraph: { spacing: { before: 300, after: 150 } },
      },
      {
        id: 'Heading3',
        name: 'Heading 3',
        basedOn: 'Normal',
        next: 'Normal',
        run: { size: 24, bold: true, color: COLORS.cyan, font: 'Bebas Neue' },
        paragraph: { spacing: { before: 250, after: 100 } },
      },
      {
        id: 'Heading4',
        name: 'Heading 4',
        basedOn: 'Normal',
        next: 'Normal',
        run: { size: 20, bold: true, color: COLORS.text, font: 'Inter' },
        paragraph: { spacing: { before: 200, after: 100 } },
      },
    ],
  },
  sections: [
    {
      properties: {
        page: {
          margin: {
            top: convertInchesToTwip(1),
            bottom: convertInchesToTwip(1),
            left: convertInchesToTwip(1),
            right: convertInchesToTwip(1),
          },
        },
      },
      headers: {
        default: new Header({
          children: [new Paragraph({
            children: [new TextRun({ text: 'FURIOUS WORLD CUP 26 — DOCUMENTAÇÃO COMPLETA', color: COLORS.fury, size: 18, font: 'Bebas Neue' })],
            alignment: AlignmentType.CENTER,
          })],
        }),
      },
      footers: {
        default: new Footer({
          children: [new Paragraph({
            children: [
              new TextRun({ text: 'Página ', color: COLORS.gray, size: 18, font: 'Inter' }),
              new TextRun({ children: [PageNumber.CURRENT], color: COLORS.gray, size: 18, font: 'Inter' }),
              new TextRun({ text: ' de ', color: COLORS.gray, size: 18, font: 'Inter' }),
              new TextRun({ children: [PageNumber.TOTAL_PAGES], color: COLORS.gray, size: 18, font: 'Inter' }),
              new TextRun({ text: '    |    FURIOUS WC26    |    Minimax AI Documentation', color: COLORS.gray, size: 18, font: 'Inter' }),
            ],
            alignment: AlignmentType.CENTER,
          })],
        }),
      },
      children: [
        // CAPA
        new Paragraph({ text: '' }),
        new Paragraph({ text: '' }),
        new Paragraph({ text: '' }),
        new Paragraph({ text: '' }),
        new Paragraph({ text: '' }),
        new Paragraph({ text: '' }),
        new Paragraph({
          children: [new TextRun({ text: 'FURIOUS WORLD CUP 26', color: COLORS.fury, size: 72, bold: true, font: 'Bebas Neue' })],
          alignment: AlignmentType.CENTER,
          spacing: { after: 200 },
        }),
        new Paragraph({
          children: [new TextRun({ text: 'DOCUMENTAÇÃO COMPLETA DO SISTEMA', color: COLORS.gold, size: 36, bold: true, font: 'Bebas Neue' })],
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 },
        }),
        new Paragraph({
          children: [new TextRun({ text: 'Álbum Digital das Copas do Mundo FIFA 2022 & 2026', color: COLORS.text, size: 28, font: 'Inter' })],
          alignment: AlignmentType.CENTER,
          spacing: { after: 100 },
        }),
        new Paragraph({
          children: [new TextRun({ text: 'Versão do Documento: 1.0.0', color: COLORS.cyan, size: 24, font: 'Inter' })],
          alignment: AlignmentType.CENTER,
          spacing: { after: 600 },
        }),
        new Paragraph({
          children: [new TextRun({ text: 'Gerado por Minimax AI', color: COLORS.gray, size: 22, font: 'Inter' })],
          alignment: AlignmentType.CENTER,
        }),
        new Paragraph({
          children: [new TextRun({ text: 'Data: 21 de Março de 2026', color: COLORS.gray, size: 22, font: 'Inter' })],
          alignment: AlignmentType.CENTER,
        }),
        new Paragraph({ children: [new PageBreak()] }),

        // ÍNDICE
        createHeading('ÍNDICE', 1),
        createParagraph('1. Visão Geral do Projeto.......................................................3'),
        createParagraph('2. Arquitetura e Tecnologia...................................................3'),
        createParagraph('3. Estrutura de Rotas..........................................................4'),
        createParagraph('4. Componentes do Sistema................................................5'),
        createParagraph('5. Serviços e Lógica de Negócio..........................................6'),
        createParagraph('6. Modelos de Dados..........................................................7'),
        createParagraph('7. Design System e Tokens Visuais......................................8'),
        createParagraph('8. Sistema de Gamificação..................................................9'),
        createParagraph('9. Economia Virtual............................................................10'),
        createParagraph('10. Sistema de Pacotes........................................................11'),
        createParagraph('11. Praça de Trocas.............................................................12'),
        createParagraph('12. Segurança e Compliance.................................................13'),
        createParagraph('13. Integrações e Dependências..........................................14'),
        createParagraph('14. Skills e Regras do Sistema............................................15'),
        createParagraph('15. Status de Implementação...............................................16'),
        new Paragraph({ children: [new PageBreak()] }),

        // SEÇÃO 1
        createHeading('1. VISÃO GERAL DO PROJETO', 1),
        createHeading('1.1 Descrição', 2),
        createParagraph('FURIOUS WORLD CUP 26 é um álbum de figurinhas digital das Copas do Mundo FIFA 2022 (Qatar) e 2026 (USA/CAN/MEX). O produto une a nostalgia dos álbuns físicos Panini com a interatividade do mundo digital, permitindo aos usuários colecionar, trocar e competir por figurinhas lendárias.'),
        createHeading('1.2 Informações do Projeto', 2),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({ children: [createTableHeader('Campo', 3000), createTableHeader('Valor', 7000)] }),
            new TableRow({ children: [createTableCell('Nome do Projeto', { shading: COLORS.graphite }), createTableCell('furious-world-cup-26')] }),
            new TableRow({ children: [createTableCell('Versão Atual', { shading: COLORS.graphite }), createTableCell('0.0.8')] }),
            new TableRow({ children: [createTableCell('Framework', { shading: COLORS.graphite }), createTableCell('Angular 21')] }),
            new TableRow({ children: [createTableCell('SSR', { shading: COLORS.graphite }), createTableCell('Angular Universal + Express')] }),
            new TableRow({ children: [createTableCell('Estilização', { shading: COLORS.graphite }), createTableCell('TailwindCSS v4 + Motion')] }),
            new TableRow({ children: [createTableCell('Inteligência Artificial', { shading: COLORS.graphite }), createTableCell('Google Gemini AI')] }),
            new TableRow({ children: [createTableCell('Porta Dev', { shading: COLORS.graphite }), createTableCell('3000')] }),
            new TableRow({ children: [createTableCell('Porta SSR', { shading: COLORS.graphite }), createTableCell('4000')] }),
          ],
        }),
        new Paragraph({ children: [new PageBreak()] }),

        // SEÇÃO 2
        createHeading('2. ARQUITETURA E TECNOLOGIA', 1),
        createHeading('2.1 Stack Tecnológico', 2),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({ children: [createTableHeader('Categoria', 3000), createTableHeader('Tecnologia', 7000)] }),
            new TableRow({ children: [createTableCell('Frontend', { shading: COLORS.graphite }), createTableCell('Angular 21 (Standalone Components, Signals)')] }),
            new TableRow({ children: [createTableCell('SSR', { shading: COLORS.graphite }), createTableCell('@angular/ssr + Express 5')] }),
            new TableRow({ children: [createTableCell('Estilização', { shading: COLORS.graphite }), createTableCell('TailwindCSS 4, PostCSS, Angular Material')] }),
            new TableRow({ children: [createTableCell('Animações', { shading: COLORS.graphite }), createTableCell('Motion (Framer Motion)')] }),
            new TableRow({ children: [createTableCell('IA', { shading: COLORS.graphite }), createTableCell('@google/genai 1.27')] }),
            new TableRow({ children: [createTableCell('Imagens', { shading: COLORS.graphite }), createTableCell('html-to-image 1.11')] }),
            new TableRow({ children: [createTableCell('PWA', { shading: COLORS.graphite }), createTableCell('@angular/service-worker')] }),
            new TableRow({ children: [createTableCell('Backend', { shading: COLORS.graphite }), createTableCell('Supabase (planejado) — mock data atual')] }),
          ],
        }),
        createHeading('2.2 Estrutura de Pastas', 2),
        createParagraph('src/'),
        createBullet('app/ — Componentes principais'),
        createBullet('  ├── app.ts/html/css — Root component'),
        createBullet('  ├── app.routes.ts — Definição de rotas'),
        createBullet('  ├── app.config.ts — Providers da aplicação'),
        createBullet('  ├── core/ — Serviços, guards, modelos'),
        createBullet('  ├── features/ — Módulos lazy-loaded'),
        createBullet('  └── shared/components/ — Componentes reutilizáveis'),
        createBullet('styles/ — CSS global (_variables, _typography, _animations)'),
        createBullet('environments/ — Configuração por ambiente'),
        createBullet('server.ts — Servidor Express SSR'),
        createBullet('main.ts / main.server.ts — Bootstrap'),
        new Paragraph({ children: [new PageBreak()] }),

        // SEÇÃO 3
        createHeading('3. ESTRUTURA DE ROTAS', 1),
        createHeading('3.1 Rotas Principais', 2),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({ children: [createTableHeader('Rota', 3500), createTableHeader('Componente', 3000), createTableHeader('Auth', 1000), createTableHeader('Descrição', 2500)] }),
            new TableRow({ children: [createTableCell('/'), createTableCell('LandingComponent'), createTableCell('Sim'), createTableCell('Landing page pública')] }),
            new TableRow({ children: [createTableCell('/auth/login'), createTableCell('LoginComponent'), createTableCell('Sim'), createTableCell('Autenticação')] }),
            new TableRow({ children: [createTableCell('/auth/register'), createTableCell('RegisterComponent'), createTableCell('Sim'), createTableCell('Cadastro')] }),
            new TableRow({ children: [createTableCell('/onboarding'), createTableCell('OnboardingComponent'), createTableCell('Não'), createTableCell('Onboarding 4 telas')] }),
            new TableRow({ children: [createTableCell('/album'), createTableCell('AlbumHomeComponent'), createTableCell('Não'), createTableCell('Home do álbum')] }),
            new TableRow({ children: [createTableCell('/album/:edition'), createTableCell('EditionViewComponent'), createTableCell('Não'), createTableCell('Copa 2022 ou 2026')] }),
            new TableRow({ children: [createTableCell('/album/:edition/:countryCode'), createTableCell('TeamViewComponent'), createTableCell('Não'), createTableCell('Seleção específica')] }),
            new TableRow({ children: [createTableCell('/album/sticker/:stickerId'), createTableCell('StickerDetailComponent'), createTableCell('Não'), createTableCell('Detalhe figurinha')] }),
            new TableRow({ children: [createTableCell('/packs'), createTableCell('PackListComponent'), createTableCell('Não'), createTableCell('Loja de pacotes')] }),
            new TableRow({ children: [createTableCell('/packs/open/:packType'), createTableCell('PackOpeningPageComponent'), createTableCell('Não'), createTableCell('Abertura de pacote')] }),
            new TableRow({ children: [createTableCell('/trading'), createTableCell('MarketplaceComponent'), createTableCell('Não'), createTableCell('Praça de trocas')] }),
            new TableRow({ children: [createTableCell('/trading/offer'), createTableCell('TradeOfferComponent'), createTableCell('Não'), createTableCell('Criar oferta')] }),
            new TableRow({ children: [createTableCell('/trading/groups'), createTableCell('TradeGroupsComponent'), createTableCell('Não'), createTableCell('Grupos de troca')] }),
            new TableRow({ children: [createTableCell('/ranking'), createTableCell('HallOfFameComponent'), createTableCell('Não'), createTableCell('Rankings')] }),
            new TableRow({ children: [createTableCell('/challenges'), createTableCell('ChallengeListComponent'), createTableCell('Não'), createTableCell('Lista de desafios')] }),
            new TableRow({ children: [createTableCell('/challenges/quiz'), createTableCell('QuizFuriaComponent'), createTableCell('Não'), createTableCell('Quiz interativo')] }),
            new TableRow({ children: [createTableCell('/profile'), createTableCell('MyProfileComponent'), createTableCell('Não'), createTableCell('Perfil do usuário')] }),
            new TableRow({ children: [createTableCell('/profile/creator'), createTableCell('StickerCreatorComponent'), createTableCell('Não'), createTableCell('Criador figurinha')] }),
            new TableRow({ children: [createTableCell('/profile/settings'), createTableCell('SettingsComponent'), createTableCell('Não'), createTableCell('Configurações')] }),
            new TableRow({ children: [createTableCell('/info/*'), createTableCell('LegalPageComponent'), createTableCell('Sim'), createTableCell('Páginas legais')] }),
            new TableRow({ children: [createTableCell('/**'), createTableCell('redirect'), createTableCell('-'), createTableCell('Fallback → /album')] }),
          ],
        }),
        createHeading('3.2 Guards', 2),
        createParagraph('authGuard (CanActivateFn): Protege rotas autenticadas. Currently mock — sempre retorna true.'),
        new Paragraph({ children: [new PageBreak()] }),

        // SEÇÃO 4
        createHeading('4. COMPONENTES DO SISTEMA', 1),
        createHeading('4.1 Componentes Compartilhados (Shared)', 2),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({ children: [createTableHeader('Componente', 3000), createTableHeader('Seletor', 3000), createTableHeader('Descrição', 4000)] }),
            new TableRow({ children: [createTableCell('BottomNavComponent'), createTableCell('app-bottom-nav'), createTableCell('Navegação inferior com 6 abas')] }),
            new TableRow({ children: [createTableCell('CookieConsentComponent'), createTableCell('app-cookie-consent'), createTableCell('Banner GDPR de consentimento')] }),
            new TableRow({ children: [createTableCell('FooterComponent'), createTableCell('app-footer'), createTableCell('Rodapé da aplicação')] }),
            new TableRow({ children: [createTableCell('PackOpeningComponent'), createTableCell('app-pack-opening'), createTableCell('Animação 9 etapas de abertura')] }),
            new TableRow({ children: [createTableCell('ProgressBarComponent'), createTableCell('app-progress-bar'), createTableCell('Barra de progresso do álbum')] }),
            new TableRow({ children: [createTableCell('SkeletonLoaderComponent'), createTableCell('app-skeleton-loader'), createTableCell('Placeholder de loading')] }),
            new TableRow({ children: [createTableCell('StickerCardComponent'), createTableCell('app-sticker-card'), createTableCell('Card individual de figurinha')] }),
          ],
        }),
        createHeading('4.2 Módulos de Feature (Lazy-loaded)', 2),
        createParagraph('Landing Module: LandingComponent'),
        createParagraph('Auth Module: LoginComponent, RegisterComponent'),
        createParagraph('Onboarding Module: OnboardingComponent + 4 sub-passos (Welcome, Team, Album Preview, First Pack)'),
        createParagraph('Album Module: AlbumHomeComponent, EditionViewComponent, TeamViewComponent, StickerDetailComponent'),
        createParagraph('Packs Module: PackListComponent, PackOpeningPageComponent'),
        createParagraph('Trading Module: MarketplaceComponent, TradeOfferComponent, TradeGroupsComponent'),
        createParagraph('Ranking Module: HallOfFameComponent'),
        createParagraph('Challenges Module: ChallengeListComponent, QuizFuriaComponent'),
        createParagraph('Profile Module: MyProfileComponent, StickerCreatorComponent, SettingsComponent'),
        createParagraph('Info Module: LegalPageComponent, Prediction2026Component, Relics2022Component'),
        new Paragraph({ children: [new PageBreak()] }),

        // SEÇÃO 5
        createHeading('5. SERVIÇOS E LÓGICA DE NEGÓCIO', 1),
        createHeading('5.1 Core Services', 2),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({ children: [createTableHeader('Serviço', 2500), createTableHeader('Responsabilidade', 7500)] }),
            new TableRow({ children: [createTableCell('UserService'), createTableCell('Estado do usuário, Fúria Coins, reputação, badges, scores Hall of Fame')] }),
            new TableRow({ children: [createTableCell('StickerService'), createTableCell('Coleção do usuário, progresso do álbum, dados mock')] }),
            new TableRow({ children: [createTableCell('PackService'), createTableCell('Lógica de abertura, rate limiting (10/min), anti-pity system, probabilidades adaptativas')] }),
            new TableRow({ children: [createTableCell('TradeService'), createTableCell('Marketplace, criação de ofertas, grupos de troca, conversão de repetidas')] }),
            new TableRow({ children: [createTableCell('GamificationService'), createTableCell('Missões diárias, badges, desafios, entradas Hall of Fame')] }),
            new TableRow({ children: [createTableCell('AudioService'), createTableCell('Efeitos sonoros por evento (login, pack_open, trade_success, etc.)')] }),
            new TableRow({ children: [createTableCell('NotificationService'), createTableCell('Push notifications para trades e desafios')] }),
            new TableRow({ children: [createTableCell('AlbumProgressService'), createTableCell('Cálculo de fases (empty/partial/most/complete), celebrações')] }),
          ],
        }),
        createHeading('5.2 Guards', 2),
        createParagraph('authGuard (CanActivateFn): Rota de proteção (atualmente mock — sempre retorna true).'),
        new Paragraph({ children: [new PageBreak()] }),

        // SEÇÃO 6
        createHeading('6. MODELOS DE DADOS', 1),
        createHeading('6.1 Interfaces Principais', 2),
        createParagraph('UserProfile: id, username, country, furyCoins, reputation, badges, hofScores, privacy'),
        createParagraph('Sticker: id, name, country, position, rarity (1-5), worldCup (2022|2026), imageUrl, stats?, verified'),
        createParagraph('Player: fullName, displayName, country (ISO 3166-1 alpha-3), position (GK|DEF|MID|FWD), dateOfBirth, worldCups, stats2022?, stats2026?, rarity, imageUrl, verified, source, lastUpdated'),
        createParagraph('Pack: id, type, cost, quantity, guarantee, contents'),
        createParagraph('TradeOffer: id, offering[], wantingAny[], wantingAll[], status, expiresAt'),
        createParagraph('Challenge: id, title, description, reward, type, expiresAt'),
        createParagraph('Mission: id, title, description, reward, type, completed'),
        createParagraph('Badge: id, name, description, criteria, tier, earnedAt?'),
        createParagraph('HallOfFameEntry: userId, category, score, rank'),
        createParagraph('Stadium: id, name, city, country, capacity, worldCup'),
        createParagraph('NationalTeam: code, name, group2022?, group2026?, cupResults'),
        createHeading('6.2 Numeração de Figurinhas', 2),
        createParagraph('Formato: [ANO]-[SIGLA]-[SEQ]'),
        createParagraph('Exemplo: 2022-BRA-01, 2026-SPECIAL-003'),
        createHeading('6.3 Hierarquia do Álbum', 2),
        createParagraph('ÁLBUM FURIOUS WC26'),
        createBullet('Copa do Mundo 2022 (Qatar)'),
        createBullet('  ├── Especiais: Capa, Introdução, Mascote, Bola Oficial, Estádios'),
        createBullet('  └── 32 Seleções: Escudo + Foto Oficial + Elenco Completo'),
        createBullet('Copa do Mundo 2026 (USA/CAN/MEX)'),
        createBullet('  ├── Especiais: Capa, Introdução, Mascote, Bola Oficial, 16 Estádios'),
        createBullet('  └── 48 Seleções: Escudo + Foto Oficial + Elenco Completo'),
        new Paragraph({ children: [new PageBreak()] }),

        // SEÇÃO 7
        createHeading('7. DESIGN SYSTEM E TOKENS VISUAIS', 1),
        createHeading('7.1 Paleta de Cores', 2),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({ children: [createTableHeader('Token', 3000), createTableHeader('Hex', 2000), createTableHeader('Uso', 5000)] }),
            new TableRow({ children: [createTableCell('--color-fury'), createTableCell('#FF2D20'), createTableCell('Primária — vermelho da marca')] }),
            new TableRow({ children: [createTableCell('--color-gold'), createTableCell('#FFD700'), createTableCell('Secundária — dourado celebrativo')] }),
            new TableRow({ children: [createTableCell('--color-night'), createTableCell('#0A0A1A'), createTableCell('Background — azul escuro')] }),
            new TableRow({ children: [createTableCell('--color-graphite'), createTableCell('#1E1E2E'), createTableCell('Cards e painéis')] }),
            new TableRow({ children: [createTableCell('--color-cyan'), createTableCell('#00E5FF'), createTableCell('Accent — ciano elétrico')] }),
            new TableRow({ children: [createTableCell('--color-text'), createTableCell('#F0F0F0'), createTableCell('Texto principal')] }),
          ],
        }),
        createHeading('7.2 Sistema de Raridades', 2),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({ children: [createTableHeader('Tier', 1000), createTableHeader('Nome', 2000), createTableHeader('Cor', 2000), createTableHeader('Prob. Base', 2000), createTableHeader('Efeito ao Revelar', 3000)] }),
            new TableRow({ children: [createTableCell('1'), createTableCell('Comum'), createTableCell('Cinza'), createTableCell('60%'), createTableCell('Estática')] }),
            new TableRow({ children: [createTableCell('2'), createTableCell('Especial'), createTableCell('Azul'), createTableCell('25%'), createTableCell('Pulse suave')] }),
            new TableRow({ children: [createTableCell('3'), createTableCell('Épica'), createTableCell('Roxo'), createTableCell('10%'), createTableCell('Partículas leves')] }),
            new TableRow({ children: [createTableCell('4'), createTableCell('Lendária'), createTableCell('Dourado'), createTableCell('4%'), createTableCell('Chamas douradas + música')] }),
            new TableRow({ children: [createTableCell('5'), createTableCell('FURIOUS'), createTableCell('Vermelho'), createTableCell('1%'), createTableCell('Explosão holográfica + confete')] }),
          ],
        }),
        createHeading('7.3 Tipografia', 2),
        createParagraph('Display: Bebas Neue — títulos e headers'),
        createParagraph('Body: Inter — texto principal'),
        createParagraph('Stats: Oswald — estatísticas numéricas'),
        createHeading('7.4 Proporções e Acessibilidade', 2),
        createParagraph('Proporção figurinha: 1:1.4 (padrão Panini)'),
        createParagraph('Toque mínimo: 44×44px'),
        createParagraph('Tela mínima suportada: 320px (iPhone SE)'),
        createParagraph('Suporte: prefers-reduced-motion'),
        new Paragraph({ children: [new PageBreak()] }),

        // SEÇÃO 8
        createHeading('8. SISTEMA DE GAMIFICAÇÃO', 1),
        createHeading('8.1 Hall da Fama — Categorias de Ranking', 2),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({ children: [createTableHeader('Categoria', 2500), createTableHeader('Critério', 4000), createTableHeader('Reset', 3500)] }),
            new TableRow({ children: [createTableCell('Grandes Colecionadores'), createTableCell('% conclusão (peso 3x lendárias)'), createTableCell('Nunca')] }),
            new TableRow({ children: [createTableCell('Primeiros a Completar'), createTableCell('Timestamp de 100%'), createTableCell('Permanente')] }),
            new TableRow({ children: [createTableCell('Caçadores de Lendárias'), createTableCell('Total de lendárias coletadas'), createTableCell('Mensal')] }),
            new TableRow({ children: [createTableCell('Mestres dos Desafios'), createTableCell('Pontos em desafios semanais'), createTableCell('Semanal')] }),
            new TableRow({ children: [createTableCell('Reis da Troca'), createTableCell('Volume e qualidade de trocas'), createTableCell('Mensal')] }),
          ],
        }),
        createHeading('8.2 Sistema de Desafios', 2),
        createParagraph('Semanais: Rotaciona toda segunda-feira (ex: "Monte o time da Copa 2022", "Quem foi o artilheiro?")'),
        createParagraph('Temáticos: Eventos especiais (Aniversário da Copa, Contagem Regressiva 2026, Dia da Final)'),
        createParagraph('Quiz Fúria: 4 opções + 30s por pergunta + streak x2 no 5º acerto seguido'),
        createHeading('8.3 Missões Diárias (Personalizadas)', 2),
        createParagraph('Álbum < 30%: missões focadas em abertura de pacotes'),
        createParagraph('Álbum 30-70%: missões focadas em trocas'),
        createParagraph('Álbum > 70%: missões focadas em desafios e lendárias'),
        createParagraph('+ Sempre 1 missão social (convidar amigo / fazer troca / visitar Praça)'),
        createHeading('8.4 Badges Chave', 2),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({ children: [createTableHeader('Badge', 3000), createTableHeader('Critério', 4000), createTableHeader('Tier', 3000)] }),
            new TableRow({ children: [createTableCell('Álbum Completo 2022'), createTableCell('100% Copa 2022'), createTableCell('Lendária')] }),
            new TableRow({ children: [createTableCell('Álbum Completo 2026'), createTableCell('100% Copa 2026'), createTableCell('Lendária')] }),
            new TableRow({ children: [createTableCell('FURIOUS'), createTableCell('Todas as FURIOUS de uma Copa'), createTableCell('FURIOUS')] }),
            new TableRow({ children: [createTableCell('Hall da Fama'), createTableCell('Top 10 em qualquer categoria'), createTableCell('Lendária')] }),
          ],
        }),
        new Paragraph({ children: [new PageBreak()] }),

        // SEÇÃO 9
        createHeading('9. ECONOMIA VIRTUAL', 1),
        createHeading('9.1 Sistema de Reputação', 2),
        createParagraph('+0.1 por troca concluída'),
        createParagraph('+0.05 por resposta rápida'),
        createParagraph('-0.3 por cancelamento'),
        createParagraph('-1.0 por report confirmado'),
        createParagraph('Range: 0.0 – 5.0'),
        createParagraph('Trader Lendário (4.5–5.0): destaque na Praça + acesso a trocas Lendárias'),
        createParagraph('Trader Iniciante (<2.5): máximo 3 trocas simultâneas'),
        createHeading('9.2 Sistema de Moeda', 2),
        createParagraph('Nome: Fúria Coins (FC)'),
        createParagraph('Carteira máxima: 10.000 FC'),
        createParagraph('Moeda nunca vence ou expira'),
        createParagraph('Taxa de ganho free-to-play não pode ser reduzida'),
        createHeading('9.3 Ganhos Free-to-Play', 2),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({ children: [createTableHeader('Fonte', 4000), createTableHeader('Coins', 2000), createTableHeader('Frequência', 4000)] }),
            new TableRow({ children: [createTableCell('Login diário'), createTableCell('20'), createTableCell('Diária')] }),
            new TableRow({ children: [createTableCell('Streak 7 dias'), createTableCell('+200'), createTableCell('Semanal')] }),
            new TableRow({ children: [createTableCell('Missão diária'), createTableCell('20–50'), createTableCell('Diária')] }),
            new TableRow({ children: [createTableCell('Desafio semanal'), createTableCell('100–300'), createTableCell('Semanal')] }),
            new TableRow({ children: [createTableCell('Troca concluída'), createTableCell('15'), createTableCell('Por troca')] }),
            new TableRow({ children: [createTableCell('Converter repetida'), createTableCell('5–100'), createTableCell('Por conversão')] }),
            new TableRow({ children: [createTableCell('Completar seleção'), createTableCell('150'), createTableCell('Por seleção')] }),
            new TableRow({ children: [createTableCell('50% do álbum'), createTableCell('500'), createTableCell('Uma vez')] }),
            new TableRow({ children: [createTableCell('100% do álbum'), createTableCell('2.000'), createTableCell('Uma vez por edição')] }),
          ],
        }),
        new Paragraph({ children: [new PageBreak()] }),

        // SEÇÃO 10
        createHeading('10. SISTEMA DE PACOTES', 1),
        createHeading('10.1 Tipos de Pacotes', 2),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({ children: [createTableHeader('Pacote', 2000), createTableHeader('Custo', 1500), createTableHeader('Quantidade', 2000), createTableHeader('Garantia', 2500), createTableHeader('Especial', 2000)] }),
            new TableRow({ children: [createTableCell('Básico'), createTableCell('100 FC'), createTableCell('5'), createTableCell('—'), createTableCell('—')] }),
            new TableRow({ children: [createTableCell('Plus'), createTableCell('180 FC'), createTableCell('10'), createTableCell('1 Especial'), createTableCell('—')] }),
            new TableRow({ children: [createTableCell('Elite'), createTableCell('300 FC'), createTableCell('20'), createTableCell('1 Épica'), createTableCell('—')] }),
            new TableRow({ children: [createTableCell('Lendário'), createTableCell('500 FC'), createTableCell('5'), createTableCell('1 Lendária'), createTableCell('—')] }),
            new TableRow({ children: [createTableCell('Copa'), createTableCell('250 FC'), createTableCell('15'), createTableCell('3 Especiais'), createTableCell('Chance FURIOUS')] }),
          ],
        }),
        createHeading('10.2 Probabilidade Adaptativa', 2),
        createParagraph('Álbum < 50% completo: boost comuns +10% — preenche base rapidamente'),
        createParagraph('Álbum 50–80% completo: boost especiais +8% — acelera fase intermediária'),
        createParagraph('Álbum > 80% completo: boost épicas +5%, lendárias +2% — final emocionante'),
        createHeading('10.3 Sistema Anti-Pity', 2),
        createParagraph('A cada 50 pacotes sem figurinha Lendária: +0.5% acumulativo até sair uma'),
        createHeading('10.4 Rate Limiting', 2),
        createParagraph('Máximo 10 aberturas por minuto por usuário'),
        createHeading('10.5 Regras de Animação', 2),
        createParagraph('Animação de abertura de pacote: 9 etapas'),
        createParagraph('Primeira abertura: não pode ser pulada'),
        createParagraph('Respeita prefers-reduced-motion'),
        new Paragraph({ children: [new PageBreak()] }),

        // SEÇÃO 11
        createHeading('11. PRAÇA DE TROCAS', 1),
        createHeading('11.1 Regras de Feed', 2),
        createParagraph('Ordenação:'),
        createBullet('1. Ofertas onde o usuário tem o que outro precisa (match parcial)'),
        createBullet('2. Ofertas de usuários seguidos'),
        createBullet('3. Ofertas do mesmo país'),
        createBullet('4. Ofertas gerais (mais recentes primeiro)'),
        createParagraph('Formato de oferta: oferecendo[] + wantingAny[] ou wantingAll[]'),
        createParagraph('Expiração: 72h após criação'),
        createHeading('11.2 Grupos de Troca', 2),
        createParagraph('Máximo 20 membros por grupo'),
        createParagraph('Tipos: Aberto / Por Convite / Secreto'),
        createParagraph('Wishlist compartilhada + sugestões automáticas de match interno'),
        createParagraph('Chat simples (mensagens retidas por 30 dias)'),
        createHeading('11.3 Regras de Troca', 2),
        createBullet('Máximo 10 trocas ativas simultâneas por usuário'),
        createBullet('Figurinha recém-recebida: cooldown de 24h para nova troca'),
        createBullet('Trocas Lendária ↔ Lendária: confirmação dupla com janela de 1h'),
        createBullet('Trocas somente entre figurinhas do mesmo tipo (jogador ↔ jogador)'),
        createBullet('Repetidas excedentes (>5 cópias): conversão automática em Fúria Coins'),
        createHeading('11.4 Filtros do Marketplace', 2),
        createParagraph('Por raridade, por seleção, por posição, por Copa'),
        createParagraph('Sort: Mais recentes, Melhor match, Por país'),
        new Paragraph({ children: [new PageBreak()] }),

        // SEÇÃO 12
        createHeading('12. SEGURANÇA E COMPLIANCE', 1),
        createHeading('12.1 Princípios de Segurança', 2),
        createParagraph('Nunca confiar no cliente — toda lógica crítica roda no servidor'),
        createParagraph('Logs de auditoria imutáveis (append-only)'),
        createParagraph('Atomicidade: moedas e trocas são transações atômicas'),
        createParagraph('Rate limiting e alertas anti-fraude'),
        createHeading('12.2 Integridade de Pacotes', 2),
        createBullet('Verificar saldo e debitar ANTES de gerar (atômico)'),
        createBullet('Gerar figurinhas com seed no servidor (nunca no cliente)'),
        createBullet('Registrar em log imutável ANTES de retornar ao cliente'),
        createBullet('Falha: reverter débito automaticamente (idempotência)'),
        createBullet('Rate limit: máximo 10 aberturas/min por usuário'),
        createHeading('12.3 Validações de Troca', 2),
        createBullet('Ambos os usuários ainda possuem as figurinhas'),
        createBullet('Nenhum está suspenso ou bloqueado'),
        createBullet('Figurinha não está em cooldown de 24h'),
        createBullet('Ambos confirmaram dentro da janela de 1h'),
        createBullet('Mesmos tipos de figurinha (jogador ↔ jogador)'),
        createBullet('Atomicidade: Ambas transferências ocorrem, ou nenhuma'),
        createHeading('12.4 Alertas Anti-Fraude', 2),
        createBullet('>10 pacotes em <1min: rate limit + revisão'),
        createBullet('>20 trocas em <1h: suspensão de trocas + revisão'),
        createBullet('Múltiplas contas no mesmo IP/device: vincular para análise'),
        createBullet('Código Fúria tentado >3x sem sucesso: bloquear por 1h'),
        createHeading('12.5 LGPD/GDPR', 2),
        createBullet('Exportar dados: até 30 dias após solicitação'),
        createBullet('Deletar conta: dados removidos em 30 dias (exceto logs de fraude)'),
        createBullet('Dados de pagamento: NUNCA armazenar raw (apenas token do processador)'),
        createBullet('Parental consent obrigatório para < 13 anos'),
        new Paragraph({ children: [new PageBreak()] }),

        // SEÇÃO 13
        createHeading('13. INTEGRAÇÕES E DEPENDÊNCIAS', 1),
        createHeading('13.1 Dependências de Produção', 2),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({ children: [createTableHeader('Biblioteca', 3000), createTableHeader('Versão', 2000), createTableHeader('Uso', 5000)] }),
            new TableRow({ children: [createTableCell('@angular/core'), createTableCell('^21.0.0'), createTableCell('Framework principal')] }),
            new TableRow({ children: [createTableCell('@angular/ssr'), createTableCell('^21.0.0'), createTableCell('Server-side rendering')] }),
            new TableRow({ children: [createTableCell('@angular/material'), createTableCell('^21.0.0'), createTableCell('Componentes UI e ícones')] }),
            new TableRow({ children: [createTableCell('@angular/service-worker'), createTableCell('^21.0.0'), createTableCell('PWA offline support')] }),
            new TableRow({ children: [createTableCell('@google/genai'), createTableCell('^1.27.0'), createTableCell('Gemini AI integration')] }),
            new TableRow({ children: [createTableCell('express'), createTableCell('^5.1.0'), createTableCell('SSR Express server')] }),
            new TableRow({ children: [createTableCell('html-to-image'), createTableCell('^1.11.13'), createTableCell('PNG generation para stickers')] }),
            new TableRow({ children: [createTableCell('motion'), createTableCell('^12.23.24'), createTableCell('Animações de UI')] }),
            new TableRow({ children: [createTableCell('tailwindcss'), createTableCell('^4.1.12'), createTableCell('Estilização utility-first')] }),
          ],
        }),
        createHeading('13.2 Variáveis de Ambiente', 2),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({ children: [createTableHeader('Variável', 3000), createTableHeader('Descrição', 7000)] }),
            new TableRow({ children: [createTableCell('GEMINI_API_KEY'), createTableCell('Google Gemini AI API key')] }),
            new TableRow({ children: [createTableCell('APP_URL'), createTableCell('URL de deploy da aplicação')] }),
            new TableRow({ children: [createTableCell('SUPABASE_URL'), createTableCell('URL do projeto Supabase (produção)')] }),
            new TableRow({ children: [createTableCell('SUPABASE_ANON_KEY'), createTableCell('Chave anônima do Supabase (produção)')] }),
            new TableRow({ children: [createTableCell('PORT'), createTableCell('Porta do servidor SSR (default: 4000)')] }),
          ],
        }),
        createHeading('13.3 Eventos de Áudio', 2),
        createParagraph('login.mp3, pack_open.mp3, trade_success.mp3, ranking_enter.mp3, album_enter.mp3, buy_pack.mp3, quiz_correct.mp3, quiz_wrong.mp3, mission_complete.mp3'),
        new Paragraph({ children: [new PageBreak()] }),

        // SEÇÃO 14
        createHeading('14. SKILLS E REGRAS DO SISTEMA', 1),
        createHeading('14.1 SK01 — Auditoria Landing Page vs. Realidade', 2),
        createParagraph('Validação de features prometidas vs. entregues com relatório de gap.'),
        createHeading('14.2 SK02 — Mecânicas Centrais do Álbum', 2),
        createParagraph('Hierarquia, raridades, probabilidade adaptativa, regras de troca, anti-pity.'),
        createHeading('14.3 SK03 — Governança de Dados', 2),
        createParagraph('Escopo exclusivo: jogadores das Copas 2022 e 2026. Pipeline de validação obrigatório.'),
        createHeading('14.4 SK04 — Gamificação e Engajamento', 2),
        createParagraph('Hall da Fama, rankings, desafios semanais, missões diárias, badges permanentes.'),
        createHeading('14.5 SK05 — Sistema Social', 2),
        createParagraph('Praça de trocas, grupos, reputação de trader, privacidade por design.'),
        createHeading('14.6 SK06 — Economia Virtual', 2),
        createParagraph('Fúria Coins, preços balanceados, monetização ética, proteção de vulnerables.'),
        createHeading('14.7 SK07 — Visual UX e Design System', 2),
        createParagraph('Paleta, tipografia, animações por raridade, onboarding 4 telas, criador de figurinha.'),
        createHeading('14.8 SK08 — Segurança e Integridade', 2),
        createParagraph('Server-side first, logs imutáveis, LGPD/GDPR, proteção de menores.'),
        createHeading('14.9 Regras Globais Imutáveis', 2),
        createBullet('Escopo do acervo: Somente jogadores das Copas de 2022 e 2026. Absoluto.'),
        createBullet('Server-side first: Toda lógica de negócio crítica é validada no servidor.'),
        createBullet('Free-to-play viável: O álbum deve ser completável sem pagamento real.'),
        createBullet('Promessas cumpridas: Nenhuma feature da landing page pode ficar sem implementação.'),
        createBullet('Dados verificados: Nenhum dado verified: false chega ao usuário final.'),
        createBullet('Atomicidade econômica: Coins e trocas são transações atômicas (tudo ou nada).'),
        createBullet('Privacidade por design: Default sempre conservador, opt-in para exposição.'),
        createBullet('Proteção de menores: Regras especiais para contas de < 13 anos, sem exceções.'),
        createBullet('Figurinhas personalizadas isoladas: Nunca se misturam com o acervo oficial.'),
        createBullet('Qualidade visual: Dark mode default, animações ricas, proporção Panini respeitada.'),
        new Paragraph({ children: [new PageBreak()] }),

        // SEÇÃO 15
        createHeading('15. STATUS DE IMPLEMENTAÇÃO', 1),
        createHeading('15.1 Resumo por Feature', 2),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({ children: [createTableHeader('Feature', 3500), createTableHeader('Status', 1500), createTableHeader('Qualidade', 2000), createTableHeader('Observações', 3000)] }),
            new TableRow({ children: [createTableCell('Landing Page'), createTableCell('✅'), createTableCell('Produção'), createTableCell('Completa')] }),
            new TableRow({ children: [createTableCell('Autenticação'), createTableCell('⚠️'), createTableCell('Mock'), createTableCell('Stub — precisa backend')] }),
            new TableRow({ children: [createTableCell('Álbum navegável'), createTableCell('✅'), createTableCell('Produção'), createTableCell('Completo com mock data')] }),
            new TableRow({ children: [createTableCell('Pacotes'), createTableCell('✅'), createTableCell('Produção'), createTableCell('Lógica completa')] }),
            new TableRow({ children: [createTableCell('Abertura de pacotes'), createTableCell('✅'), createTableCell('Produção'), createTableCell('Animação 9 etapas')] }),
            new TableRow({ children: [createTableCell('Trading/Marketplace'), createTableCell('⚠️'), createTableCell('Mock'), createTableCell('UI pronta, lógica mock')] }),
            new TableRow({ children: [createTableCell('Grupos de troca'), createTableCell('⚠️'), createTableCell('Mock'), createTableCell('UI pronta, lógica mock')] }),
            new TableRow({ children: [createTableCell('Ranking/Hall of Fame'), createTableCell('✅'), createTableCell('Produção'), createTableCell('5 categorias')] }),
            new TableRow({ children: [createTableCell('Desafios'), createTableCell('⚠️'), createTableCell('Parcial'), createTableCell('Quiz funcional')] }),
            new TableRow({ children: [createTableCell('Missões diárias'), createTableCell('⚠️'), createTableCell('Parcial'), createTableCell('UI/Service ready')] }),
            new TableRow({ children: [createTableCell('Perfil do usuário'), createTableCell('✅'), createTableCell('Produção'), createTableCell('Completo')] }),
            new TableRow({ children: [createTableCell('Sticker Creator'), createTableCell('✅'), createTableCell('Produção'), createTableCell('Upload + IA + PNG')] }),
            new TableRow({ children: [createTableCell('Settings'), createTableCell('✅'), createTableCell('Produção'), createTableCell('Completo')] }),
            new TableRow({ children: [createTableCell('SSR/PWA'), createTableCell('✅'), createTableCell('Produção'), createTableCell('Service worker ativo')] }),
            new TableRow({ children: [createTableCell('Backend (Supabase)'), createTableCell('❌'), createTableCell('Planejado'), createTableCell('Atualmente mock data')] }),
            new TableRow({ children: [createTableCell('Phygital/Código Fúria'), createTableCell('❌'), createTableCell('Planejado'), createTableCell('Resgate de códigos')] }),
            new TableRow({ children: [createTableCell('Push Notifications'), createTableCell('⚠️'), createTableCell('Beta'), createTableCell('Service pronto')] }),
            new TableRow({ children: [createTableCell('Onboarding'), createTableCell('✅'), createTableCell('Produção'), createTableCell('4 telas')] }),
          ],
        }),
        createHeading('15.2 Legenda de Status', 2),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            new TableRow({ children: [createTableHeader('Símbolo', 1500), createTableHeader('Significado', 4000), createTableHeader('Qualidade', 4500)] }),
            new TableRow({ children: [createTableCell('✅'), createTableCell('Implementado'), createTableCell('Pronto para produção ou mock funcional')] }),
            new TableRow({ children: [createTableCell('⚠️'), createTableCell('Parcialmente implementado'), createTableCell('UI pronta mas lógica em mock/beta')] }),
            new TableRow({ children: [createTableCell('❌'), createTableCell('Não implementado'), createTableCell('Planejado ou não iniciado')] }),
          ],
        }),
        createHeading('15.3 Prioridades para Próximas Fases', 2),
        createParagraph('P0 (Bloqueante):'),
        createBullet('Backend Supabase — autenticação real, persistência de dados'),
        createBullet('Lógica server-side para pacotes (anti-fraude)'),
        createBullet('Lógica server-side para trocas (atomicidade)'),
        createParagraph('P1 (Alta):'),
        createBullet('Integração Supabase para marketplace real'),
        createBullet('Sistema de notificação push funcional'),
        createBullet('Sistema de Código Fúria (phygital)'),
        createParagraph('P2 (Média):'),
        createBullet('Chat nos grupos de troca'),
        createBullet('Deep links e compartilhamento social'),
        createBullet('Mais dados de jogadores verificados'),
        createParagraph('P3 (Baixa):'),
        createBullet('Modo offline completo'),
        createBullet('Tutorial interativo'),
        createBullet('Eventos sazonais avançados'),
        new Paragraph({ text: '' }),
        new Paragraph({ text: '' }),
        new Paragraph({
          children: [new TextRun({ text: '— FIM DO DOCUMENTO —', color: COLORS.fury, size: 24, bold: true, font: 'Bebas Neue' })],
          alignment: AlignmentType.CENTER,
          spacing: { before: 400 },
        }),
        new Paragraph({
          children: [new TextRun({ text: 'FURIOUS WORLD CUP 26 — Documentação Minimax AI v1.0.0', color: COLORS.gray, size: 20, font: 'Inter' })],
          alignment: AlignmentType.CENTER,
        }),
        new Paragraph({
          children: [new TextRun({ text: '21 de Março de 2026', color: COLORS.gray, size: 20, font: 'Inter' })],
          alignment: AlignmentType.CENTER,
        }),
      ],
    },
  ],
});

// Gerar o documento
Packer.toBuffer(doc).then((buffer) => {
  fs.writeFileSync('DOCUMENTACAO_MINIMAX.docx', buffer);
  console.log('✅ DOCUMENTACAO_MINIMAX.docx gerado com sucesso!');
  console.log('📁 Localização: C:\\Users\\ViniciusL\\Documents\\Antigravity\\furious-world-cup-26\\DOCUMENTACAO_MINIMAX.docx');
}).catch((err) => {
  console.error('❌ Erro ao gerar documento:', err);
  process.exit(1);
});
